### ISSUE TITLE
Discrepancy between README and implementations of GELU estimate

### ISSUE THREAD

**Issue by lostmsu** [hendrycks/GELUs#1]
In the README: `0.5 * x * (1 + tanh(x * 0.7978845608 * (1 + 0.044715 * x * x)))`
In TF and others: `0.5 * _x * (1 + tf.tanh(tf.sqrt(2 / np.pi) * (_x + 0.044715 * tf.pow(_x, 3))))`

Note, in the README x is squared at the end, while in the implementations it is cubed.

**Comment by hendrycks** [comment]
Notice the x preceding 0.7978845608. I wrote it in this way following [Horner's method](https://en.wikipedia.org/wiki/Horner's_method).
