### ISSUE TITLE
Where to find the TIMIT dataset?

### ISSUE THREAD

**Issue by islamazhar** [hendrycks/GELUs#3]
https://github.com/hendrycks/GELUs/blob/2726505c4767eed99dfd89ce0f836fbca44d6a6d/timit_fcn.py#L139

Can you point to any link for downloading the train.h5, dev.h5 and core.h5 files for TIMIT datasets?
Thanks in advance!

**Comment by hendrycks** [comment]
TIMIT requires a license so is not publicly available.
